packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.13
  '@lexical/code': ^0.40.0
  '@lexical/link': ^0.40.0
  '@lexical/list': ^0.40.0
  '@lexical/markdown': ^0.40.0
  '@lexical/react': ^0.40.0
  '@lexical/rich-text': ^0.40.0
  '@rslint/tsgo': ^0.2.0
  '@stricli/core': ^1.2.5
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.6
  '@types/node': ^25.2.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@types/ws': ^8.18.1
  '@vitejs/plugin-react': ^5.1.3
  clsx: ^2.1.1
  cors: ^2.8.6
  express: ^5.2.1
  lefthook: ^2.0.16
  lexical: ^0.40.0
  lucide-react: ^0.563.0
  pkgroll: ^2.23.0
  react: ^19.2.4
  react-dom: ^19.2.4
  react-router-dom: ^7.13.0
  repojj: ^2026.1.35
  sonner: ^2.0.7
  tailwindcss: ^4.1.18
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vitest: ^2.1.9
  ws: ^8.19.0

catalogMode: strict

cleanupUnusedCatalogs: true
