packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  default:
    # Dependencies
    "@lexical/code": "^0.39.0"
    "@lexical/link": "^0.39.0"
    "@lexical/list": "^0.39.0"
    "@lexical/markdown": "^0.39.0"
    "@lexical/react": "^0.39.0"
    "@lexical/rich-text": "^0.39.0"
    "@tailwindcss/typography": "^0.5.19"
    "clsx": "^2.1.1"
    "cors": "^2.8.5"
    "express": "^4.18.2"
    "lexical": "^0.39.0"
    "lucide-react": "^0.563.0"
    "react": "^19.2.0"
    "react-dom": "^19.2.0"
    "react-router-dom": "^7.13.0"
    "sonner": "^2.0.7"
    "ws": "^8.16.0"
    
    # Dev Dependencies
    "@eslint/js": "^9.39.1"
    "@tailwindcss/vite": "^4.1.18"
    "@types/react": "^19.2.5"
    "@types/react-dom": "^19.2.3"
    "@vitejs/plugin-react": "^5.1.1"
    "concurrently": "^8.2.2"
    "eslint": "^9.39.1"
    "eslint-plugin-react-hooks": "^7.0.1"
    "eslint-plugin-react-refresh": "^0.4.24"
    "globals": "^16.5.0"
    "tailwindcss": "^4.1.18"
    "vite": "^7.2.4"
