packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@eslint/js': ^9.39.2
    '@lexical/code': ^0.39.0
    '@lexical/link': ^0.39.0
    '@lexical/list': ^0.39.0
    '@lexical/markdown': ^0.39.0
    '@lexical/react': ^0.39.0
    '@lexical/rich-text': ^0.39.0
    '@tailwindcss/typography': ^0.5.19
    '@tailwindcss/vite': ^4.1.18
    '@types/cors': ^2.8.19
    '@types/express': ^5.0.6
    '@types/react': ^19.2.10
    '@types/react-dom': ^19.2.3
    '@types/ws': ^8.18.1
    '@vitejs/plugin-react': ^5.1.2
    clsx: ^2.1.1
    concurrently: ^8.2.2
    cors: ^2.8.6
    eslint: ^9.39.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    express: ^4.22.1
    globals: ^16.5.0
    lexical: ^0.39.0
    lucide-react: ^0.563.0
    react: ^19.2.4
    react-dom: ^19.2.4
    react-router-dom: ^7.13.0
    sonner: ^2.0.7
    tailwindcss: ^4.1.18
    vite: ^7.3.1
    ws: ^8.19.0
